### ISSUE TITLE
Feature request: allow specification of login page

### ISSUE THREAD

**Issue by foxylearning** [Full-Stack-Press/Frill-SSO-Unofficial#1]
Many WordPress sites (especially those using WooCommerce or membership plugins) do not use the standard WordPress login page. It would be great if the admin could specify the URL users are redirected to for login.

**Comment by samuelbengtsson** [comment]
This is a great idea, and we will add it for sure after it has been released on WordPress.org

**Comment by samuelbengtsson** [comment]
This has been added in the latest version 1.0.3
