### ISSUE TITLE
Instructions Step 3.

### ISSUE THREAD

**Issue by jessetuttle** [Full-Stack-Press/Frill-SSO-Unofficial#2]
**Reported from the Facebook Group**
Step 3 of the plugin installation instructions reads "Go to 'Single Sign-On' and input your redirect URL. This is the URL for your Frill site, like 'https://feedback.example.com.'" I interpreted "your Frill site" to be the custom subdomain I use for my Frill site, but that does not work. I had to enter my regular website's URL as the redirect URL to get it to work.

**Comment by samuelbengtsson** [comment]
This was corrected in the version 1.0.1
